services:
  db:
    image: postgres:16.10-alpine3.22
    container_name: numbers_app_db
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: numbers_app
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data
    networks:
      - numbersnet

  server:
    build: ./server
    container_name: numbers_app_server
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://app_user:app_password@db:5432/numbers_app
      JWT_SECRET: setup_some_key_here_that_should_be_changed_and_kept_secret
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - numbersnet

  client:
    build: ./client
    container_name: numbers_app_client
    restart: always
    depends_on:
      - server
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - numbersnet

volumes:
  db_data:

networks:
  numbersnet:
    driver: bridge
